sun-sunDayz/mamilha

- frontend/App.js
- frontend/src/screens/CreateGroup.js
- frontend/src/screens/FinancesDetail.js
- frontend/src/screens/UpdateGroup.js
finances Detail frontend 완성 
아직 backend와는 연결 안했습니다.  finances 완성 후에 연결
> finances Detail frontend 완성

- frontend/babel.config.js
- frontend/package.json
- frontend/src/screens/Main.js
- frontend/src/services/apiClient.js
* apiClient를 사용하여 통신관련 기능 통합
* dotenv, cookies 등을 사용한 환경 변수 설정
> feat apiClient를 사용한 axios 적용

- backend/groups/views.py
- frontend/src/screens/Login.js
- frontend/src/screens/Main.js
- frontend/src/services/apiClient.js
* 로그인 토큰 설정 기능 추가
* Main.js에 테스트 코드 추가
> 로그인 및 토큰 관련 코드 추가

- backend/config/settings.py
- backend/groups/views.py
- frontend/ios/Podfile.lock
- frontend/package.json
- frontend/src/components/GroupMember.js
- frontend/src/screens/CreateGroup.js
- frontend/src/screens/FinancesDetail.js
- frontend/src/screens/UpdateGroup.js
- group update backend 멤버 추가시 기좀멤버 이름이 삭제되는 문제 해결
- 그룹 추가와 그룹 수정 frontend를 backend와 연결
> Feature/create groups 

- frontend/App.js
- frontend/src/components/Currency.js
- frontend/src/components/FinanceForm.js
- frontend/src/components/GroupCategory.js
- frontend/src/components/Spending.js
- frontend/src/screens/CreateFinance.js
- frontend/src/screens/CreateGroup.js
- frontend/src/screens/FinanceDetail.js
- frontend/src/screens/Finances.js
- frontend/src/screens/Main.js
- frontend/src/screens/UpdateFinance.js
- frontend/src/screens/UpdateGroup.js
1. 기존에 axios로 된 부분들 apiClient로 변경
2. FinanceFrom 컴포넌트에 group_pk 값 전달 밑 연결 
3. 뒤로가기 아이콘에 navigation추가
> axios 변경, 뒤로가기 추가

- backend/finances/urls.py
- backend/finances/views.py
- backend/groups/urls.py
- backend/groups/views.py
- frontend/package.json
- frontend/src/components/FinanceForm.js
backend 
1. Finance Category 관리를 위해 API View 제작 및 연결
2. group API View 이름 수정
forntend 
1. finance form 데이터 이름 수정
2. finance update 시 기존 데이터 출력되도록 변경
> FinanceForm 수정 

- frontend/src/screens/Login.js
frontend
* 로그아웃 시 아이디, 비밀번호 값 남아있는 부분 초기화되도록 수정
> fix 로그아웃 이슈 수정

- frontend/src/components/Spending.js
> fix finance 카테고리 DB 색상 적용

- backend/finances/views.py
- backend/groups/views.py
- backend/models.py
- backend/urls.py
- frontend/src/components/FinanceCategory.js
- frontend/src/components/FinanceForm.js
- frontend/src/components/GroupMember.js
- frontend/src/components/Payer.js
- frontend/src/components/UpdateMember.js
- frontend/src/screens/CreateGroup.js
- frontend/src/screens/Main.js
- frontend/src/screens/Profile.js
- frontend/src/screens/UpdateGroup.js
- frontend/src/services/apiClient.js
내 정보 - Header Title 수정 (Profile.js)
UpdateGroup - 삭제 기능 추가 (+ 삭제 후 리프레쉬)
Main.js - 모임 삭제 수정 시 리프레쉬 및 삭제된 모임 안 보이게 처리
DropDown 수정 완
> 드롭다운 통일 & 모임 삭제 기능 추가

- backend/groups/models.py
- backend/groups/views.py
- frontend/src/components/GroupForm.js
- frontend/src/screens/InviteGroup.js
- frontend/src/screens/InviteGroupDetail.js
- frontend/src/screens/InviteGroupDetailNew.js
- frontend/src/screens/UpdateGroup.js
* GroupForm에 맞게 모임 코드 생성 추가
* 모임명, 모임장 정상적으로 표기되도록 수정
> fix 초대코드 관련 버그 수정

- backend/groups/views.py
- frontend/src/components/ButtonGroup.js
- frontend/src/components/GroupForm.js
- frontend/src/screens/Finances.js
- frontend/src/screens/InviteGroupDetail.js
- frontend/src/screens/InviteGroupDetailNew.js
- frontend/src/screens/SignUp.js
초대코드 입장 인터페이스 개선
- 관리자는 선택에서 제외
- 이미 입장한 경우 입장된 상태로 적용
초대코드 생성 딜레이 시간 적용
> 초대코드 관련 세부 기능 추가

- backend/groups/views.py
backend 
1. 빈 멤버 값 추가 시 발생하는 유효성 검사 추가
> 그룹생성 검사 오류 해결

- frontend/src/components/Spending.js
- frontend/src/components/Split.js
* 지출/이체 내역 없을 시 default 화면 출력되도록 수정
> fix 지출/이체 내역 default 화면 출력

- backend/groups/views.py
> fix 초대받기 관련 버그 수정

- backend/groups/views.py
- frontend/src/components/GroupForm.js
- frontend/src/components/GroupMember.js
- frontend/src/screens/CreateGroupMember.js
- frontend/src/screens/UpdateGroupMember.js
* 연동된 계정이 없을 경우 아이디, 등급 보이지 않도록 수정
* 멤버 리스트에서 관리자 계정 편집 불가하도록 수정
> fix 계정 연동 관련 이슈 수정

- frontend/src/components/FinanceForm.js
- frontend/src/components/GroupListItem.js
- frontend/src/components/Split.js
- frontend/src/screens/FinanceDetail.js
- frontend/src/screens/UpdateGroup.js
Frontend 
1. 이체 클릭 시 구분 ‘이체’로 설정
2. 이체 클릭 시 멤버 부분 이슈 해결
3. 그룹 이름 15자 이상 시 '...'으로 표시 되도록 설정
4. 지출 등록 결제자 없어도 등록 가능 이슈 해결
5. alert 모든 화면 Alert.alert로 변경
> form 오류 수정

- frontend/src/components/Spending.js
- frontend/src/components/Split.js
Frontend
1. 지출/이체 딜레이 오류 로딩 추가로 해결
> 지출/이체 로딩 추가

- frontend/src/components/Spending.js
- frontend/src/components/Split.js
Frontend
1. 지출/이체 빠르게 전환시 이전과 같은 오류발생 해결
> 지출/이체 빠르게 전환시 오류발생

- backend/finances/views.py
- backend/init.py
- frontend/src/components/Split.js
Backend
1. inint.py 이체 카테고리 12 추가
Frontend
1. 이체 클릭 시 지출 카테고리, 결제자 아이디 설정
> 이체등록 오류 해결

- backend/.dockerignore
- backend/config/settings.py
- backend/dockerfile
- backend/nginx.conf
- docker-compose.yml
backend 
1. 배포 ALLOWED_HOSTS 변경
2. dockerfile 설정 변경 
3. docker-compose.yml 파일 설정 변경
> 배포 docker 설정

- frontend/src/components/GroupForm.js
- frontend/src/screens/Intro.js
Frontend 
1. 어플 로딩화면 추가 및 토큰값 확인 후 화면 이동 구현
2. 그룹 생성 시 멤버 입력창 스타일 오류 수정
> 로그인 유지기능 추가

- frontend/android/app/build.gradle
- frontend/android/app/src/main/AndroidManifest.xml
- frontend/android/app/src/main/res/xml/network_security_config.xml
- frontend/android/gradle.properties
- frontend/src/services/apiClient.js
> fix 안드로이드 배포시 http 문제로 동작 안되는 문제 수정

- backend/nginx.conf
- docker-compose.yml
> nginx 파일 수정
